version: 2.1

commands: 
  setup-automation:
    steps:
      - run:
          name: Setup automation
          command: |
            git submodule update --init --recursive
            ./deps/readies/bin/getpy3
            ./deps/readies/bin/getpy2
            python3 ./deps/readies/bin/system-setup.py

jobs:
  build-and-test-bionic:
      docker:
        - image: 'ubuntu:bionic'
      steps:
        - run:
            name: Setup executor
            command: |
              apt-get -qq update
              apt-get -q install -y git openssh-client curl ca-certificates make tar gzip python3-dev unzip python-pip maven
        - checkout
        - setup-automation
        - run:
            name: Install Redis
            command: ./deps/readies/bin/getredis --version 6
        - run:
            name: Install RLTest
            command: python2.7 -m pip install --no-cache-dir git+https://github.com/RedisLabsModules/RLTest.git@master
        - run:
            name: Tests
            command: make tests
        - run:
            name: Pack
            command: make pack
        - persist_to_workspace:
            root: artifacts
            paths:
              - 'snapshot/*.tgz'
  build-and-test-centos:
      docker:
        - image: 'centos:centos7'
      steps:
        - run:
            name: Setup executor
            command: |
              yum install -y git openssh-client curl ca-certificates make tar gzip python-devel python3-devel.x86_64 unzip maven
        - run:
            name: Install centos-release-scl
            command: |
              yum install -y centos-release-scl
        - run:
            name: Install gcc 8
            command: |
              yum install -y devtoolset-8
        - checkout
        - setup-automation
        - run:
            name: Install semantic_version
            command: python3 -m pip install --no-cache-dir semantic_version
        - run:
            name: Install Redis
            command: . /opt/rh/devtoolset-8/enable; ./deps/readies/bin/getredis --version 6
        - run:
            name: get pip
            command: |
              curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
              python get-pip.py
        - run:
            name: Install RLTest
            command: python2.7 -m pip install --no-cache-dir git+https://github.com/RedisLabsModules/RLTest.git@master
        - run:
            name: Tests
            command: . /opt/rh/devtoolset-8/enable; make tests
        - run:
            name: Pack
            command: make pack
        - persist_to_workspace:
            root: artifacts
            paths:
              - 'snapshot/*.tgz'
  deploy_snapshots:
      docker:
        - image: redisfab/rmbuilder:6.0.9-x64-buster
      steps:
        - attach_workspace:
            at: artifacts
        - run:
            name: Deploy Snapshots to S3
            command: |
              for f in artifacts/snapshot/*.tgz; do
                aws s3 cp $f s3://redismodules/redisgears_plugins/jvm_plugin/snapshots/ --acl public-read
              done
on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

on-master: &on-master
  filters:
    branches:
      only: master

after-build-and-test: &after-build-and-test
  requires:
    - build-and-test-bionic
    - build-and-test-centos

workflows:
  version: 2
  commit:
    jobs:
      - build-and-test-bionic:
          <<: *on-any-branch
      - build-and-test-centos:
          <<: *on-any-branch
      - deploy_snapshots:
          <<: *after-build-and-test
          <<: *on-master

  nightly:
      triggers:
        - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only:
                  - master
      jobs:
        - build-and-test-bionic
        - build-and-test-centos
